version: '3.7'

services:
  kratos-migrate:
    image: oryd/kratos
    environment:
      - DSN=postgres://kratos:secret@postgresd:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
    volumes:
      - type: bind
        source: ./contrib/quickstart/kratos/email-password
        target: /etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure
    networks:
      - intranet

  kratos:
    image: oryd/kratos
    depends_on:
      - kratos-migrate
    environment:
      - DSN=postgres://kratos:secret@postgresd:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    volumes:
      - type: bind
        source: ./contrib/quickstart/kratos/email-password
        target: /etc/config/kratos
    ports:
      - '4433:4433' # public
      - '4434:4434' # admin
    networks:
      - intranet
    restart: unless-stopped

  postgresd:
    image: postgres:11.8
    ports:
      - "5432:5432"
    command: [ "postgres", "-c", "wal_level=logical" ]
    environment:
      - POSTGRES_USER=kratos
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DATABASES=kratos
    networks:
      - intranet
    restart: unless-stopped

  iam-postgresd:
    image: postgres:11.8
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_USER=iam
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DATABASES=iam
    networks:
      - intranet
    restart: unless-stopped

  kratos-selfservice-ui-node:
    image: oryd/kratos-selfservice-ui-node:v1.1.0
    ports:
      - "4455:4455"
    environment:
      - PORT=4455
      - SECURITY_MODE=
      - KRATOS_PUBLIC_URL=http://kratos:4433/
      - KRATOS_BROWSER_URL=http://127.0.0.1:4433/
      - COOKIE_SECRET=minhdqsecret
      - CSRF_COOKIE_NAME=ory_csrf_ui
      - CSRF_COOKIE_SECRET=minhdqsecret2
    networks:
      - intranet
    restart: on-failure
  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - '4436:4436'
      - '4437:4437'
    networks:
      - intranet

  kafka1:
    image: 'bitnami/kafka:3.4'
    container_name: kafka1
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka1:9092
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka1:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_KRAFT_CLUSTER_ID=r4zt_wrqTRuT7W2NJsB_GA
    volumes:
      - volume1:/bitnami/kafka
    ports:
      - "9092:9092"
    networks:
      - intranet
  kafka-ui:
    container_name: kafka-ui
    image: 'provectuslabs/kafka-ui:latest'
    ports:
      - "8888:8080"
    environment:
      - KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS=kafka1:9092
      - KAFKA_CLUSTERS_0_NAME=r4zt_wrqTRuT7W2NJsB_GA
    networks:
      - intranet

  debezium-connect:
    image: debezium/connect:2.3
    container_name: cdc-using-debezium-connect
    restart: always
    ports:
      - '8083:8083'
    environment:
      - BOOTSTRAP_SERVERS=kafka1:9092
      - GROUP_ID= 1
      - CONFIG_STORAGE_TOPIC= my_connect_configs
      - OFFSET_STORAGE_TOPIC= my_connect_offsets
      - STATUS_STORAGE_TOPIC= my_connect_statuses
      - ENABLE_DEBEZIUM_SCRIPTING= 'true'
    links:
      - kafka1
      - postgresd
    networks:
      - intranet

networks:
  intranet:
    driver: bridge
    external: false
volumes:
  volume1: